project:
  type: website
  output-dir: docs

website:
  title: "Anderson Neisse"
  navbar:
    right:
      - href: posts.qmd
        text: Posts
      - href: projects.qmd
        text: Projects
      - href: papers.qmd
        text: Papers
      - href: talks.qmd
        text: Talks

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: false



