---
title: "Talks"
page-layout: full
---

This page serves as a centralized hub for my most pertinent talks, providing easy access to both the talks themselves and the accompanying slides.

::: column-screen-inset-right
| Date | Title | Slides | Summary |
|---------|:-----|:------:|:------|
| may/2023 | **Da análise exploratória ao aprendizado de máquina: Estatísticos na área de dados** |     [🖥️](/_slides/stats-week-viii-2023/stats_career_on_ds_2023.pdf "Slides"){aria-label="Lab 2 slides"} | A talk made during the 8th Statistics Week of the Federal University of Mato Grosso. I talked a little about my own career and some topics i judged important for statisticians planning to enter the Data Science job market at the time. |
| jun/2022 | **Estatística no Tribunal de Justiça do Estado de Mato Grosso** |     [🖥️](/_slides/stats-week-vii-2022/stats-at-tjmt.pdf "Slides"){aria-label="Lab 2 slides"} | A talk made during the 7th Statistics Week of the Federal University of Mato Grosso, presenting the data ecosystem present at the Mato Grosso State Court for the statisticians and other data professionals who work there to navigate on and generate value. |
| Multiple | **R Markdown: Introdução, aplicações e extensões** |     [🖥️](/_slides/rmd-tutorial/rmarkdown-tutorial.html "Slides"){aria-label="Lab 2 slides"} | A R Markdown tutorial for people who never had any contact with it before hand, covering a wide range of use cases. |
| jul/2019 | **Chronic Fatigue Syndrome: Relations with absenteeism** | [🖥️](/_slides/64rbras-2019/64rbras-cfs-absenteeism.html "Slides"){aria-label="Lab 2 slides"} |   Talk on the 64th RBras, on Cuiabá-MT, Brazil, on the topic of Chronic Fatigue Syndrome and its relations with absenteeism, assessed with Elastic-net and Stepwise methods.|
| jun/2018 | **Reamostragem Bootstrap: Introdução, variações e implementação com processamento paralelo** | [🖥️](/_slides/bootstrap-variations-2019/bootstrap-variations-paralel.html "Slides"){aria-label="Lab 2 slides"} | A seminar on the various Bootstrap methods and its implementations in R using parallele processing for performance gains.|
:::


